#!/bin/bash
mkdir -p install
# Yosys, Yosys plugins and Surelog will be installed in the $PREFIX location
export PREFIX=$(pwd)/install
# This variable is required in Yosys build system to link against Surelog and UHDM
export UHDM_INSTALL_DIR=$(pwd)/install

export PATH=$PREFIX/bin:$PATH
if [[ -z $VIVADO_PATH ]]
then
 echo "Export vivado settings path"
 exit 1
fi


pip3 install virtualenv
virtualenv env
source env/bin/activate

source $VIVADO_PATH

git clone https://github.com/alainmarcel/Surelog --recurse-submodules
cd Surelog && git checkout b1d3c0efc11ed2f37091b7d10b06f5a36ba6d984 --recurse-submodules
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_POSITION_INDEPENDENT_CODE=ON -S . -B build
cmake --build build -j $(nproc)
cmake --install build
cd -

git clone https://github.com/yosyshq/yosys
cd yosys && git checkout 1cac671c70bc3da9808ceb3add15686da4a5d82e
patch -p1 -N < ../uhdm.patch
make -j$(nproc) install
cd -

git clone https://github.com/antmicro/yosys-symbiflow-plugins
cd yosys-symbiflow-plugins && git checkout 4cab7813de5b295f6caabc01795c8c53d3befd69
git submodule update --init --recursive
make install -j$(nproc)
cd -

wget https://raw.githubusercontent.com/lowRISC/opentitan/master/util/get-toolchain.py
python3 get-toolchain.py -i lowrisc-toolchain
export PATH=$(realpath lowrisc-toolchain/bin):$PATH

git clone https://github.com/lowrisc/ibex
cd ibex && git checkout ac8934459b028220ce9fd20683bb018244b59756
cd -

cd ibex/examples/sw/led/
make
cd -

pip3 install -r ibex/python-requirements.txt
pip3 install git+https://github.com/antmicro/edalize@uhdm_support

cd ibex && git am ../0001-add-synth-surelog-target.patch && git am ../0002-ibex-change-ram_2p-to-ram_1p.patch
cd -

fusesoc --cores-root=$(realpath ibex) run --build --tool yosys \
--target=synth lowrisc:ibex:top_artya7_surelog \
--SRAMInitFile="$(realpath ibex/examples/sw/led/led.vmem)"


fusesoc --cores-root=$(realpath ibex) run --build --tool vivado \
--target=synth lowrisc:ibex:top_artya7_surelog \
--SRAMInitFile="$(realpath ibex/examples/sw/led/led.vmem)"
